[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = '0.8.20'
fs_permissions = [
  { access = "read", path = "./out" },
  { access = "read-write", path = "./deployments" },
]

[profile.deploy]
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
tab_width = 4
func_attrs_with_params_multiline = true
ignore = ["lib/**", "src/v*/Groth16Verifier.sol", "src/v*/PlonkVerifier.sol", "src/v*/zksync/PlonkVerifier.sol"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"
hoodi = "${RPC_HOODI}"
arbitrum = "${RPC_ARBITRUM}"
arbitrum_sepolia = "${RPC_ARBITRUM_SEPOLIA}"
base = "${RPC_BASE}"
base_sepolia = "${RPC_BASE_SEPOLIA}"
optimism = "${RPC_OPTIMISM}"
optimism_sepolia = "${RPC_OPTIMISM_SEPOLIA}"
scroll = "${RPC_SCROLL}"
scroll_sepolia = "${RPC_SCROLL_SEPOLIA}"
hyperevm = "${RPC_HYPEREVM}"
plasma = "${RPC_PLASMA}"
monad = "${RPC_MONAD}"
mega = "${RPC_MEGA}"
xlayer = "${RPC_XLAYER}"
bsc = "${RPC_BSC}"
tempo = "${RPC_TEMPO}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=1" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=11155111" }
hoodi = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=560048" }
arbitrum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=42161" }
arbitrum_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=421614" }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=8453" }
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=84532" }
optimism = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=10" }
optimism_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=11155420" }
scroll = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=534352" }
scroll_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=534351" }
hyperevm = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=999" }
bsc = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=56" }
monad = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=143" }
mega = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=4326" }
plasma = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=9745" }
xlayer = { key = "${OKLINK_API_KEY}", url = "https://www.oklink.com/api/v5/explorer/contract/verify-source-code-plugin/XLAYER" }
tempo = { key = "unused", url = "https://contracts.tempo.xyz/api" }
